# Generated by Django 2.0.6 on 2018-06-26 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='uploads/image')),
                ('desc', models.CharField(blank=True, max_length=100, verbose_name='图片描述')),
            ],
        ),
    ]
