# Generated by Django 2.0.6 on 2018-06-26 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_image', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='desc',
        ),
    ]
