# Generated by Django 2.0.6 on 2018-06-20 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='comment_nums',
        ),
    ]
