# Generated by Django 2.0.6 on 2018-06-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blog_comment_nums'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='thumb_img',
            field=models.CharField(blank=True, max_length=200, verbose_name='摘要缩略图'),
        ),
    ]
