# Generated by Django 2.0.6 on 2019-04-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190405_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
